export const CartTypes = {
  ADD_REQUESTED: '@cart/ADD_REQUESTED',
  REMOVE_REQUESTED: '@cart/REMOVE_REQUESTED',
  MODIFY_SUCCEEDED: '@cart/MODIFY_SUCCEEDED',
  ADD_VOUCHER_REQUESTED: '@cart/ADD_VOUCHER_REQUESTED',
  ADD_VOUCHER_SUCCEEDED: '@cart/ADD_VOUCHER_SUCCEEDED'
}
